### ISSUE TITLE
AirSend problème de Status remonté

### ISSUE THREAD

**Issue by Wind06** [devmel/hass_airsend#13]
Hello,

J'essaye d'utiliser AirSend sur Home Assistant, j'ai installé AirSend ainsi que le module local.
Tout c'est bien passé, j'ai recupérer le fichier .yaml de ma configuration sur le cloud et j'ai créer mon fichier airsend.yaml 
et je l'ai référencé dans configuration.yaml

après relance de HACS, et je retrouve mes volets avec commandes up/stop/down, mais avec un status unknown.
Je descends le volet le status devient  "Fermé", et l'icône passe de Ouvert a fermé. 
Je remonte le volet et la le status reste "Fermé" et icône reste fermé....

Je n'arrive pas a comprendre comment je peux fixer ce soucis.

Merci

**Comment by Tarjaizaid** [comment]
Hello,

Tu as toujours la problématique ?

Pour ma part, cela fonctionne, j'ai ce genre de message dans les logs du addon Airsend :
PHP Notice:  state_post  : cover.voletroute **open** in /home/hassapi.class.php on line 264

As tu également ces messages ?

(si cela peut t'aider à trouver la cause)

**Comment by Wind06** [comment]
Hello,

tout fonctionne correctement maintenant, j'avais une erreur de configuration locale.
par contre dans mon fichier aisend.yaml j'ai passé tous les volets en type:4099 au lien de 4098.
ce qui me permet d'avoir un retour d'état plus cohéran.

J'utilise également le Mushroom cover pour les volets, ce qui m'a permis de mettre des pseudo état et changement de couleur en fonction de l'état des volets.

PS: le support airsend m'avait quand même dit la chose suivante 
Avec spurl il est possible que l’addon n’arrive pas a communiquer avec ha et il faut ajouter
wait: true
pour chaque appareil dans airsend.yaml

**Comment by Wind06** [comment]
Problème fixé.
