### ISSUE TITLE
Error while upgrading to HA 2024.10

### ISSUE THREAD

**Issue by joanmarty** [devmel/hass_airsend#14]
When moving to HA 2024.10, some sensor are not working anymore. It sound that previous sensor naming for airsend is  not anymore compatible with this new version of HA.

**Comment by nicotontige** [comment]
Found an fix
In the __init__.py file, you must replace the method "async_get_addon_info" by "async_get_addon_discovery_info"
I'll create a PR

**Comment by joanmarty** [comment]
[home-assistant_2024-10-18T12-53-22.676Z.log](https://github.com/user-attachments/files/17435673/home-assistant_2024-10-18T12-53-22.676Z.log)

I have installed the update 2024.10.2 and here is the log I have about airsend issue

**Comment by nicotontige** [comment]
`[homeassistant.setup] Unable to prepare setup for platform 'airsend.switch': Platform not found (cannot import name 'async_get_addon_info' from 'homeassistant.components.hassio' (/usr/src/homeassistant/homeassistant/components/hassio/__init__.py)).`
Please update the hass_airsend code.
The method "_async_get_addon_info_" has been removed in the the HA version 2024.10
Tell me if it solved the issue (got another solution if not)

**Comment by joanmarty** [comment]
Field was not available on the V1.0 I had on local installation. I removed the local version to move on the V1.2 version of airsend addon.
