### ISSUE TITLE
One button type command is associated to a switch command

### ISSUE THREAD

**Issue by jujupointcom** [devmel/hass_airsend#2]
Hello,
First of all, thanks for this job !
I have mapped a command in airsend GW which is a simple "one button" command. It is stateless. Each push on the button send a command in the sequence : open - stop - close - stop. It is linked to a gate motor.
In Home Assistant, with this AirSend integration, this command, which type is "4096" in the AirSend.yaml, is associated to a switch (as 4097). I guess 4097 corresponds to real switch (with on and off states). 
Would it be possible to create a new mapping in the integration to map 4096 type to a simple button object in HA ? 
Thanks,
Julien

**Comment by jujupointcom** [comment]
Hi,
I can provide code to have a 1-button mapped to ButtonEntity in HA / Switch mapping remains for "4097" type in previous code.
Let me know if you want to get it.
Regards

**Comment by jouralexandre** [comment]
Hello,
Yes you can make a "pull request" or send us the zip of your code to apps@devmel.com with pleasure.

Thanks a lot,

**Comment by jujupointcom** [comment]
Hello Alexandre,

When do you think the fix will be embedded into a release ? Currently, when
installing AirSend extension in HA using the "wget" command download 1.0
release. I have the same question for the add-on you have just fixed as
well (thanks !!) after the issue I have opened.

FYI : on peut poursuivre en Français nos échanges.

Julien

**Comment by jouralexandre** [comment]
Hello,
Releases are updated.
Thanks,
