### ISSUE TITLE
Problème a la première commande d'appel de service 

### ISSUE THREAD

**Issue by Iroamstaff** [devmel/hass_airsend#9]
Quand mes volets ne sont pas utilisés pendant un certain temps la première commande exécuté ne fonctionne pas et produit une erreur. Les commandes suivantes qui sont faites dans la foulée fonctionne parfaitement sans produire d'erreur 
Donc après un certain temps sans utilisation pour ouvrir ou femme un volet j'appuie une fois l'erreur ce produit et une deuxième pour que la commande soit prise en compte. 
Je joins les log ha 

Cette erreur provient d'une intégration personnalisée

Logger: airsend
Source: custom_components/airsend/device.py:171
Integration: AirSend (documentation)
First occurred: 30 juin 2023 à 01:01:15 (9 occurrences)
Last logged: 5 juillet 2023 à 10:28:42

Transfer error 'Volet chambre parentale' : '500'
Transfer error 'Volet Ch1 Etage' : '500'
Transfer error 'Volet Sdb Etage' : '500'

Autre erreur qui apparaît dans le log ha 

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/airsend/device.py:172
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 30 juin 2023 à 01:01:15 (7 occurrences)
Last logged: 5 juillet 2023 à 10:28:43

[547070776528] Transfer error Volet Ch1 Etage : 500
[546963666448] Transfer error Volet Ch1 Etage : 500
[547070080080] Transfer error Volet Ch1 Etage : 500
[546961604560] Transfer error Volet Sdb Etage : 500
[546728642576] Transfer error Volet Ch1 Etage : 500
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 337, in async_open_cover
    await self.hass.async_add_executor_job(ft.partial(self.open_cover, **kwargs))
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/airsend/cover.py", line 83, in open_cover
    if self._device.transfer(note):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/airsend/device.py", line 172, in transfer
    raise Exception("Transfer error " + self.name + " : " + str(status_code))
Exception: Transfer error Volet chambre parentale : 500

Si je pouvais avoir de l'aide pour régler ce problème je serai très reconnaissant merci

**Comment by falconslag** [comment]
Salut,

J'ai aussi le code retour 'erreur 500 ' quand j'utilise Home Assistant pour piloter mes volets. Je ne l'ai pas (en tout cas pas constaté) quand j'utilise l'application sur SmartPhone.

J'ai contourné le problème en installant le module complémentaire pour utilisation en local. Et en local, je n'ai plus aucune 'Erreur 500'. Je ne pense pas que cela vienne techniquement du boitier ou des volets. Je pencherai plutôt pour un délai d'établissement de session un peu plus long à destination du Cloud qui ferait suite à une inactivité un peu longue. Peut-être lié à la négociation du jeton de session...

Je n'ai pas regardé le code pour savoir s'il y avait moyen de modifier un time out pour l'augmenter.

je confirme que c'est pénible, surtout dans les automatisations, car le code retour 500 stoppe toute la chaine.

En mode local, ça marche bien.

Après, à faire confirmer par le support Devmel (plutôt réactif en général), mais il est possible que certains protocoles ne soient fonctionnels qu'en mode airsend.cloud et pas en local.

Je vais leur poser la question...

**Comment by Iroamstaff** [comment]
Je suis en Local sur home assistant et j'ai cette erreur, avec Home assistant en cloud je l'avais aussi. Avec l'application airsend cloud je n'ai aucun problème mais je ne l'utilise pas. Comme tu le précises c'est la communication entre Home assistant et le boîtier airsend ou ça coince mais seulement la première commande après tout fonctionne.

**Comment by falconslag** [comment]
Iroamstaff,

Chaque environnement pose un verrou sur le boîtier au moment de passer une commande:
- L'interface Web airsend.cloud
- L'appli Smartphone
- Le module local

C'est empirique, mais quand j'avais l'erreur, j'ai eu l'impression que si je laissais une page web ouverte quelque part, j'avais plus d'occurrence. Mais c'est purement un ressenti.

Par contre, ce qui est certain, c'est que je n'ai plus eu aucune erreur de ce type depuis que je passe en local. Après il est aussi vrai qu'avec le temps plus ensoleillé, j'ai une automation qui ferme les volets au delà d'une certaine température. Du coup, ça me fait un accès en journée que je n'avais pas en hiver où seule la fermeture auto se faisait le soir à la nuit tombée.
Ca conserve peut-être une connexion ou session active, et donc réduit le délai de la première commande.

Si tu as un équipement qui par exemple ne réagit pas au stop quand il ne fait rien, essaie de mettre une automatisation qui l'exécute en milieu de journée et regarde si ça change quelque chose.

Pour ma part j'ai des stores Profalux et le stop ne sert qu'à arrêter une montée ou descente. Si l'erreur se reproduit cette hiver, je testerai aussi mon idée.

@+
Falcon

**Comment by Iroamstaff** [comment]
Très  bonne idée. Je vais essayer une ou plusieurs automatisation avec le bouton Stop. C'est des moteurs de volet battant Thomson donc aucun souci. 
Merci pour ton aide en espérant que ça règle ce problème

**Comment by Iroamstaff** [comment]
Au top fonctionne j'ai créé une automatisation qui fait stop toute les 6h et j'ai plus aucun problème
Un grand merci a toi @falconslag
